### ISSUE TITLE
Update Example with next-preactx-plugin

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/first-preact-app#12]
# Motivation
Update the repo with next-preactx-plugin

# Tasks
- [x] Import new plugin
- [x] Be able to make it work locally.
- [x] Verify it works on heroku.
