### ISSUE TITLE
Remove React Dependency

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/first-preact-app#16]
# Motivation
We want to remove React and React Dom and all the other plugins as Next plugins will not be updated for the forseeable future.

# Tasks
- [ ] Use Link-Module-Alias isntead of module-alias.
- [ ] Initiate Scripts and _moduleAliases to bypass NextJS's entrypoint Check.
- [ ] Remove React, React-Dom and next-preactx-plugin.
- [ ] Be able to build.
