### ISSUE TITLE
Implement NextJS over app

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/first-preact-app#3]
# Motivation
We want to be able to be able to render this app on the server side. 

# Tasks
- [x] Import nextjs.
- [x] Read up.
- [x] Move infrastructure to nextjs.
- [x] Import and remove necessary packages.
- [x] Add compatibility packages.
- [x] Be able to run locally.
