### ISSUE TITLE
Work with Next 8

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/first-preact-app#7]
# Motivation
We want to make this work with NextJS 8 instead of relying on a rollback to NextJS 7. This is due to the current set of proposed changes from pull request https://github.com/zeit/next.js/issues/6265 currently not being published to NPM, so we'll be doing this ourselves.

# Tasks
- [x] Look over the Issue and pull request.
- [x] Manually add files over to this example project.
- [x] Add extra dependencies to go around Context Error.
- [x] Run.
