### ISSUE TITLE
Make Repository compatible with Preact X and Next 8.1.0

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/first-preact-app#9]
# Motivation
Now that Next has had some updates and Preact X has hooks, we want to be able to utilize preact hooks in future projects. 

# Tasks
- [ ] Replace NPM with yarn commands.
- [ ] Add credits.
- [ ] Update all dependencies.
- [ ] Use the credit example to be able to build the new version of the app.
- [ ] Use the a counting demonstration for preact hooks.
- [ ] Remove old preact-next files.
